sudo: required
services:
  - docker

before_install:
  - docker build -t erlds5518/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true erlds5518/react-test npm test

after_success:
  - docker build -t erlds5518/multi-client  ./client
  - docker build -t erlds5518/multi-nginx   ./nginx
  - docker build -t erlds5518/multi-server  ./server
  - docker build -t erlds5518/multi-worker  ./worker
  
  # Log in to the docker CLIE
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push to docker hub
  - docker push erlds5518/multi-client
  - docker push erlds5518/multi-nginx
  - docker push erlds5518/multi-server
  - docker push erlds5518/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-250859683430'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY